<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-1J7MGPJ" name="Test" tests="2" failures="1" timestamp="26 Apr 2019 17:23:06 GMT" time="136.285" errors="0">
  <testcase name="testValidLogin" time="10.388" classname="scripts.TestValidLogin">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at scripts.TestValidLogin.testValidLogin(TestValidLogin.java:29)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
  <testcase name="testInvalidLogin" time="75.884" classname="scripts.TestInvalidLogin"/>
</testsuite> <!-- Test -->
